name: laochampa
favicon: null
layout_spectrum: 0.0336582544259727
typography_spectrum: 0.9705538472626358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.29286281298846006
  lightness: 0.20799469202756882
  saturation: 0.38107128464616835
  rhythmicContrast: 0.8760849174577743
purpose: []
